### ISSUE TITLE
Todo list - week 11

### ISSUE THREAD

**Issue by ycui0008** [ycui0008/ETC5543-intro-R#6]
- [ ]  Start writing the report
- [ ]  Complete 90% of the project
- [ ] Make sure citing journal articles
- [ ] Find more data set 
- [ ] Create more questions in shiny
