### ISSUE TITLE
Todo list - week 10

### ISSUE THREAD

**Issue by ycui0008** [ycui0008/ETC5543-intro-R#7]
- [ ] Fix the display issue in section 1
- [ ] Fix the comparison issue of user entries and example solutions
- [ ] Have a score system in shiny
